### ISSUE TITLE
conf.py error too after make menuconfig i happen error one and two by the line of command make

### ISSUE THREAD

**Issue by Azaretdodo** [ROCm/ROCK-Kernel-Driver#156] opened 2023-12-19 14:28 UTC
Hello there,

I copy paste from my phone because the system is an Ubuntu server so for conf.py and i don't use ssh:

`conf.py line 32 in module
major, minor, patch = sphinx.version_info[:3]
AttributeError module sphinx has no attribute version_info`

Thus if i remove version_info i happen error following :

`conf.py line 32 in module
major, minor, patch = sphinx
TypeError cannot unpack non-iterable module objet`

In addition if i remove the line 32 then i define major  (this is asked)finally for the errors python :

`load_config.py line 6 in module
from sphinx.util.osutil import fs_encoding
ModuleNotFoundError no module named sphinx.util`

For go more far i remove the line six in load_config fortunately i really go more far for happen error following :

`conf.py line 60 in module
if major >= 3
TypeError >= not supportés between instances of fonction and int`

Therefore for the errors make :

`make 1 *** scripts/Makefile.host:110: scripts/sign-file error 1
make *** Makefile:1270 scripts error 2`

For finish my explaining thanks you in advance to bring a program who works fully,

Regards.

Azaretdodo.

**Comment by Azaretdodo** [comment] 2024-08-21 10:24
Hello,


The problems stay again because these last day i was renew my Ubuntu server with this programs where i was add some dependencies ask by it program's shell as for exemples bison ... Flex ... Libssl ... Finally rockm still brokens with unkow errors however i was install rockm with tar gz link not the last because the last misses kmod files and make fils so if you know you can advice short command line for learn the rockm version but i keep the file installer where i can read the rockm version thus too i can learn to yourself the jenskin hack last who attack World IT also i have test install this programs using make with more CPU core and using the default make who is too broken without i think this hack,

Thanks you in advance for your help,

Sorry for the problems but github will become better,

Have a nice week,

Regards.


Azaretdodo.

________________________________
De : ppanchad-amd ***@***.***>
Envoyé : mardi, août 20, 2024 4:33:11 PM
À : ROCm/ROCK-Kernel-Driver ***@***.***>
Cc : Azaretdodo ***@***.***>; Mention ***@***.***>
Objet : Re: [ROCm/ROCK-Kernel-Driver] conf.py error too after make menuconfig i happen error one and two by the line of command make (Issue #156)


@Azaretdodo<https://github.com/Azaretdodo> Apologies for the lack of response. Can you please check if your issue still exist with the latest ROCm 6.2? If not, please close the ticket. Thanks!

**Comment by Azaretdodo** [comment] 2024-08-21 13:22
Hello,


The problems stay again because these last day i was renew my Ubuntu server with this programs where i was add some dependencies ask by it program's shell as for exemples bison ... Flex ... Libssl ... Finally rockm still brokens with unknow errors (i have follown both first step advice by this website without success ( https://www.malekal.com/erreur-debian-canonical-certs-pem-compilation-noyau/ ) however i was install rockm with tar gz link (version 6.0.0 too broken by it own certificat in addition i attach in attachment a picture who show the error happening) not the last because the last misses kmod files and make files so too i can learn to yourself the jenskin hack last who attack World IT (shown in this website : https://thehackernews.com/2024/08/cisa-warns-of-critical-jenkins.html )also i have test install this programs using make with more CPU core and using the default make who is too broken by i think this hack,

Thanks you in advance for your help,

Sorry for the problems but github will become better,

Have a nice week,

Regards.


Azaretdodo.
________________________________

**Comment by ppanchad-amd** [comment] 2024-08-21 15:22
@Azaretdodo Internal ticket has been created to investigate your issue. Thanks!

**Comment by schung-amd** [comment] 2024-08-22 14:42
Hi @Azaretdodo, I'll need some more information:

- Operating system
- CPU
- GPU
- ROCm version
- Output of `/opt/rocm/bin/rocminfo --support`

What exactly is the issue and when/how does it occur? You mention conf.py, but as far as I understand this is just for building documentation. If you're trying to build the documentation, then your initial `sphinx`-related error indicates that you need to update `sphinx`.

You also mention installing ROCm from a tarball; I recommend installing using the installer according to https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/detailed-install.html. If you want to install a specific version, you can modify these instructions to pull in that version from repo.radeon.com; for example, if you want 6.0.0 on Ubuntu 22.04, you can replace 
```
wget https://repo.radeon.com/amdgpu-install/6.2/ubuntu/jammy/amdgpu-install_6.2.60200-1_all.deb
sudo apt install ./amdgpu-install_6.2.60200-1_all.deb
```
with
```
wget https://repo.radeon.com/amdgpu-install/6.0/ubuntu/jammy/amdgpu-install_6.0.60000-1_all.deb
sudo apt install ./amdgpu-install_6.0.60000-1_all.deb
```
For older versions you may have to look up the version-specific installation guide.

**Comment by Azaretdodo** [comment] 2024-08-23 08:40
hello,


initially the system is an ubuntu server noble numbat editing (24.04 LTS) secondly the processor is the intel i5 10500 thirdly i haven't any gpu but i know the motherboard is a msi torpedo series so either is an intel APU or an AMD APU fourdly the rocm version was from the tarbal 6.0.0 fifthly i switch from kubuntu to the ubuntu server where rocm is installed thus i will bring a picture taken from my phone for show the answer of your command line by a file attachment unfortunately none file rocminfo found but i attach the picture taken with the phone for shown the happening in addition the command line `locate rocminfo` should show where your advice is stored but none advice file stored now for answer your advice where you said install from the default also i answer as the old answer i was talken sixthly you seem broken from the hacking against jenskin langage (this is the langage who created all files make) sevendly i won't install your debian files advice because maybe the APU is an Intel APU finally if you want help from an IT army developer (french and myself) i type my short e-mail here ***@***.*** ,

Thanks you in advance for your help,

Have a nice weekend,

Regards.


Azaretdodo.

________________________________
De : schung-amd ***@***.***>
Envoyé : jeudi 22 août 2024 16:42
À : ROCm/ROCK-Kernel-Driver ***@***.***>
Cc : Azaretdodo ***@***.***>; Mention ***@***.***>
Objet : Re: [ROCm/ROCK-Kernel-Driver] conf.py error too after make menuconfig i happen error one and two by the line of command make (Issue #156)


Hi @Azaretdodo<https://github.com/Azaretdodo>, I'll need some more information:

  *   Operating system
  *   CPU
  *   GPU
  *   ROCm version
  *   Output of /opt/rocm/bin/rocminfo --support

What exactly is the issue and when/how does it occur? You mention conf.py, but as far as I understand this is just for building documentation. If you're trying to build the documentation, then your initial sphinx-related error indicates that you need to update sphinx.

You also mention installing ROCm from a tarball; I recommend installing using the installer according to https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/detailed-install.html. If you want to install a specific version, you can modify these instructions to pull in that version from repo.radeon.com; for example, if you want 6.0.0 on Ubuntu 22.04, you can replace

wget https://repo.radeon.com/amdgpu-install/6.2/ubuntu/jammy/amdgpu-install_6.2.60200-1_all.deb
sudo apt install ./amdgpu-install_6.2.60200-1_all.deb


with

wget https://repo.radeon.com/amdgpu-install/6.0/ubuntu/jammy/amdgpu-install_6.0.60000-1_all.deb
sudo apt install ./amdgpu-install_6.0.60000-1_all.deb


For older versions you may have to look up the version-specific installation guide.

**Comment by schung-amd** [comment] 2024-08-23 14:39
Hi, some points for clarification.

- What exactly is the issue and when/how does it occur? You mention conf.py, but as far as I understand this is just for building documentation. If you're trying to build the documentation, then your initial sphinx-related error indicates that you need to update sphinx.
- You say you're on an APU with no GPU but not sure if it's Intel or AMD; can you verify? Does your system have an accelerator card like the MI series?
- rocminfo should be present in your ROCm install directory, so look in there if you have installed ROCm somewhere other than the default install directory. If this isn't present anywhere on your system, then ROCm did not install correctly.

**Comment by Azaretdodo** [comment] 2024-08-23 15:18
Firstly the error happen either with `make` and `make -j 3` nor `make install` nor `make -j 3 install` secondly i checked on the web this motherboard support Crossfire so the APU is an AMD finally as i was said rocminfo is nill way because locate hasn't found in addition your problem for the last rocm went maybe from the jenskin hacking however i don't know if i am hacked at home fortunately i will search AMD chipset APU update because i think it miss for this setup,

Thanks you in advance for your help,

Regards.


Azaretdodo.
________________________________

**Comment by Azaretdodo** [comment] 2024-08-23 15:41
Firstly the error happen either with `make` and `make -j 3` nor `make install` nor `make -j 3 install` all by a certificate debian / canonical error secondly i checked on the web this motherboard support Crossfire so the APU is an AMD finally as i was said rocminfo is in a nill area because locate hasn't found in addition your problem for the last rocm went maybe from the jenskin hacking however i don't know if i am hacked at home fortunately i will search AMD chipset APU update because i think it miss for this setup,

Thanks you in advance for your help,

Regards.


Azaretdodo.
________________________________

**Comment by schung-amd** [comment] 2024-08-23 17:41
Is there an error other than the sphinx error in your original post? This can be addressed by updating sphinx on your system. If there are other errors, please provide full details of the output you're seeing as well as the steps to reproduce these errors. Additionally, motherboard support for crossfire does not indicate that you have AMD hardware. If you are using an Intel processor with no discrete GPU or accelerator, then you are using Intel integrated graphics alone, in which case this kernel driver is not appropriate.

**Comment by Azaretdodo** [comment] 2024-08-25 18:45
I have installed AMD GPU driver without errors then for explain the other error i am happening so this is a certificate error but however i don't know why i should update sphinx when the file setup.py is missing in your work than you bring,

Thanks you in advance for your help,

Regards.


Dorian Rosse.
________________________________

**Comment by Azaretdodo** [comment] 2024-08-26 07:51
Hello,


I have installed AMD GPU driver without errors then i attach in attachment the printscreen error about the certificate missing so if you have a let's encrypt tutorial this is good finally about sphinx i don't understand why you talk about because in your fork the setup.py file is missing,

Thanks you in advance for your help,

Regards.


Azaretdodo.
________________________________

**Comment by schung-amd** [comment] 2024-08-27 14:02
Hi, the `sphinx` module update suggestion is to address the error seen in your initial post (i.e. `conf.py line 32 in module major, minor, patch = sphinx.version_info[:3] AttributeError module sphinx has no attribute version_info`) if you are still experiencing it.

I don't see an attached image, please resend it. Where does the missing certificate error show up?

**Comment by Azaretdodo** [comment] 2024-08-27 19:28
Hello,


i attached in attachment the printscreen error however i don't understand where the problem happen about the certificate missing so if you have a let's encrypt tutorial this is good finally about sphinx i don't happening because in your fork the setup.py<http://setup.py/> file is missing,

Thanks you in advance for your help,

Regards.


Azaretdodo.
________________________________

**Comment by Azaretdodo** [comment] 2024-08-28 11:13
Hello,


I pass the certificate error by installing two dependancies so python3-sphinx for compile the kernel and gdb who is missing for the file python called vmlinux.py<http://vmlinux.py/> unfortunately vmlinux doesn't find any gdb module nor python 2 and python 3 gdb too the aptitude packager doesn't find any dependancies other than gdb so i attach in attachement three picture taken with my phone thus the make error and the error happen with vmlinux.py<http://vmlinux.py/> and how is type this python file therefore i have edited this file it happen strange error about gdb,

Thanks you in advance to help myself fully use rock kernel driver,

Regards.


Azaretdodo.
________________________________

**Comment by schung-amd** [comment] 2024-08-28 13:42
I can't find any references to a file named `vmlinux.py` in our repo. Do you mean `vmlinux-gdb.py`? I also cannot see any images you have attached, you may have to comment directly on GitHub instead of emailing in order for them to show up. It's difficult to investigate this without knowing the exact error you're running into here.

**Comment by Azaretdodo** [comment] 2024-08-28 19:02
Hello,


I pass the certificate error by installing two dependancies so `python3-sphinx` for compile the kernel and `gdb` who is missing for the file python called `vmlinux.py` however without switch on Ubuntu server because the system always power on is kubuntu also the file name can be `vmlinux-gdb.py` seen than `gdb` is one of the variable module used unfortunately `vmlinux-gdb.py` doesn't find any `gdb` module nor python 2 and python 3 `gdb` too the aptitude packager doesn't find any dependancies other than `gdb` so i attach in attachement three picture taken with my phone thus the make error and the error happen with `vmlinux-gdb.py` and how is type this python file therefore i have edited this file it happen strange error about `gdb`
![IMG_20240828_130449](https://github.com/user-attachments/assets/29e5bc1c-76b6-4f87-8580-7cf8242ed43e)
![IMG_20240828_130247](https://github.com/user-attachments/assets/9a058023-cc9c-4b58-b674-068b993c0f67)
![IMG_20240828_125505](https://github.com/user-attachments/assets/f44e0ec6-e800-4274-8e24-6e18f47dfbb8)
,

Thanks you in advance to help myself fully use rock kernel driver,

Regards.


Azaretdodo.

**Comment by schung-amd** [comment] 2024-09-03 13:56
It looks like `make` is not completing, which may be related to the error you're seeing mentioning `gdb`. You can try to bypass this by telling `cmake` not to treat warnings as errors, or by silencing this particular warning.

**Comment by Azaretdodo** [comment] 2024-09-04 09:35
Hello,


So i create a build directory then i go inside this directory and i launch `cmake ..` ?

Thanks you in advance for your help,

Regards.


Dorian Rosse.
________________________________

**Comment by schung-amd** [comment] 2024-09-04 20:28
The process you've tried before should be correct, but you'll need to pass additional options in the makefile or when you invoke `make`; for example, the advice in https://stackoverflow.com/questions/8132594/disable-werror-in-configure-file and https://stackoverflow.com/questions/11750988/quick-way-to-override-werror-flag might work. You may want to selectively disable the specific warning which is erroring out here with something like `CFLAGS=-Wno-error=frame-larger-than`.

**Comment by Azaretdodo** [comment] 2024-09-05 12:34
Hello,


Now the error happen on the line 2030 from the makefile so i don't do your advice because the compiler go more far without do your advice thus if you know how to repaire the error happening from the line 2030 on the makefile you are welcome,

Thanks you in advance,

Regards.


Dorian Rosse.
________________________________

**Comment by schung-amd** [comment] 2024-09-05 13:40
Could you attach an image of any error you see? I can't tell what's going on without the error output.

**Comment by Azaretdodo** [comment] 2024-09-05 15:50
It was just happen something as `error 2 makefile line 2030`

Thanks you in advance to help myself,

Regards.


Azaretdodo.
________________________________

**Comment by schung-amd** [comment] 2024-09-20 12:45
Sorry for the delay. I'll need the actual error message to help you here.

**Comment by Azaretdodo** [comment] 2024-09-21 08:59
Hello,


I went to down my gamer screen for power on my Ubuntu server where it is installed rock kernel driver so i log in github for attach the printscreen taken with my phone where i show the error already explained

![IMG_20240921_104659](https://github.com/user-attachments/assets/49b935d5-a7d3-490e-a620-fff2df6747a5)

Thus now your help will be welcome and if you haven't the time take a good weekend,

Thanks you in advance,

Regards.


Azaretdodo.

**Comment by Azaretdodo** [comment] 2024-09-28 07:40
Hello,


After have update the system now `rockm` compile more fast without few line and i understand with the phasing where is the error happening with this programs consequently both errors happening on the `certificate` not added and the subprogram `fs` who is linked to `mdadm` who failed to set the system as a raid one system (`fs` is the failed state program) thus i attach the picture taken with my phone where i show the shell not working for use an arrow for print the building in a text file in addition the errors happening with the fork program and finally i show the program who are phasing,

![IMG_20240928_082835](https://github.com/user-attachments/assets/029bbc06-6e58-45ca-a432-28386b6ce193)
![IMG_20240928_083000](https://github.com/user-attachments/assets/07431bb3-9a2f-4b48-b0e9-3ff4d6dd401c)
![IMG_20240928_083237](https://github.com/user-attachments/assets/41fe0cca-6bf2-4439-af84-61cfb2dbc58b)

If you think i need a `certificate` you can bring to myself a good french tutorial video nor an english website explaining the repairing because i had search a tutorial without succes however there was some years i was success to add a certificate fortunately i had a Synology NAS,

All others help are welcome seen they haven't only the certificate problem,

Thanks you in advance for your help,

Regards.


Azaretdodo.

**Comment by schung-amd** [comment] 2024-09-30 18:24
You can try some of the advice in https://stackoverflow.com/questions/67670169/compiling-kernel-gives-error-no-rule-to-make-target-debian-certs-debian-uefi-ce, it seems relevant to your cert-related error. As for the `fs` error, as I mentioned above this is because cmake is treating that warning as an error, and you may be able to bypass this.

**Comment by Azaretdodo** [comment] 2024-10-01 09:21
Hello,


I need a real tutorial about the certificate problem because after have follow your link my problem stay in addition your adviced link isn't enough explain because inside the last advice talk about a linux kernel directory without explain where and too it advice to install the last real kernel however it doesn't work too in addition the problems of the real kernel seems be the same,

Thanks you in advance to bring a better tutorial,

Regards.


Azaretdodo.
________________________________

**Comment by schung-amd** [comment] 2024-10-01 20:08
If you're not building a signed kernel (i.e. for secure boot), you can remove the check for certs with 
```
scripts/config --disable SYSTEM_TRUSTED_KEYS
scripts/config --disable SYSTEM_REVOCATION_KEYS
```
after you generate the config file with `make menuconfig`. If you need these certs, you will have to install the Ubuntu kernel sources and find them there. If you need to do this, I can help you figure out where they are.

Note that this is for building the entire kernel along with the drivers. If you just need the drivers for your system you should install them through the package manager or somewhere else they are provided separately.

**Comment by Azaretdodo** [comment] 2024-10-03 09:02
Hello,


Your help doesn't work because it miss the config directory nor config file also i paste a picture taken with my phone who show you both advice can't work

![IMG_20241003_105500](https://github.com/user-attachments/assets/0c1f040f-a00f-443f-938d-7d3efbdb5530)

Finally thanks you in advance to bring me a real tutorial for your fork,

Regards.


Azaretdodo.

**Comment by Azaretdodo** [comment] 2024-10-03 09:25
Hello,


Your advice don't work as show the picture taken with the phone also you need to bring a real help because config is missing in your fork finally thanks you in advance to bring a real help,

![IMG_20241003_105500](https://github.com/user-attachments/assets/d45e0e9c-d770-4eca-8148-f89804ec1b24)

Regards.


Azaretdodo.

**Comment by schung-amd** [comment] 2024-10-03 14:17
Again, note that this is for building the kernel and not just the drivers; if you want just the drivers, you should get them elsewhere. That being said, if you do want to proceed with building the kernel from source, there are several guides available to do this, although not specific to this repo. 

For example, you can try the instructions at https://itsfoss.com/compile-linux-kernel/. You're currently on the "Configuring the Linux kernel" step. The instructions I've given to disable the keys should be done in the "Modifying the configuration" step, where you can either find where to set them in `make menuconfig` or just run the commands I provided to modify the config file.

**Comment by Azaretdodo** [comment] 2024-10-06 13:46
Hello and happy sunday from the France,


I follew your link adviced also i don't get the sign of the default kernel and i happening others errors that i show using my phone caméra :

![IMG_20241006_150343](https://github.com/user-attachments/assets/759ead67-0160-4509-af75-f2f98fb612b5)
![IMG_20241006_151048](https://github.com/user-attachments/assets/ca63e6e8-31cf-41f4-91f2-10f7546eb5b3)
![IMG_20241006_151300](https://github.com/user-attachments/assets/095367a1-b021-44e0-8c45-1c13157c9da1)
![IMG_20241006_152913](https://github.com/user-attachments/assets/26e8c933-87d6-4bf5-8316-c77dee1b1799)
![IMG_20241006_153106](https://github.com/user-attachments/assets/acd92178-d249-474d-8b3e-a4034625bd4d)
![IMG_20241006_153405](https://github.com/user-attachments/assets/ef0c4662-8aab-4d07-b472-549803aa6639)
![IMG_20241006_153602](https://github.com/user-attachments/assets/c39def1d-3624-418d-8937-7f5df973cacb)

In addition i tried Rock kernel driver after did disable the certificate but both failed by keeping the certificate as errors,

Thanks you in advance to help myself fully repair the kernels,

Regards.


Azaretdodo.

**Comment by schung-amd** [comment] 2024-10-07 14:07
I can see you've disabled MODULE_SIG in your config as suggested by the tutorial, but have you also disabled SYSTEM_TRUSTED_KEYS and SYSTEM_REVOCATION_KEYS as I suggested?

Also, you do not have to use `-pratham` as the tag for this, that is just the tutorial author's name; you can use anything you want here.

**Comment by Azaretdodo** [comment] 2024-10-08 09:45
Hello,


Also i have melted your advices who disable for catch with my phone the output then i have write both big kernel program with the name pratham for again catch the output with my phone finally i paste here the catch :

![IMG_20241008_110856](https://github.com/user-attachments/assets/bd1c409f-6684-452a-920c-3020cb7dd1bc)
![IMG_20241008_111634](https://github.com/user-attachments/assets/0ebf6434-4945-4d41-a6b8-8ce7527d8c4d)
![IMG_20241008_111745](https://github.com/user-attachments/assets/72f43a6a-6401-4257-9f1c-c266636c13bc)
![IMG_20241008_112917](https://github.com/user-attachments/assets/689421ff-519b-498b-b228-7877376cee58)
![IMG_20241008_113950](https://github.com/user-attachments/assets/1ef58451-118d-4eb5-9661-8686d5d4b024)

Thanks you in advance to help myself fully repair this programs,

Regards.


Azaretdodo.

**Comment by schung-amd** [comment] 2024-10-08 13:38
Is there a more descriptive error somewhere upstream? "Error 2" does not provide any information.

Also, I would like to clarify again. The steps you are taking here are for building the entire Linux kernel, not just the ROCK kernel driver. This kernel is included with the driver but not required for it to function. If you only need the driver I recommend installing it with `amdgpu-install`.

**Comment by Azaretdodo** [comment] 2024-10-08 18:29
Hello,


If you know how to read the error log with the command line `sudo make -j 3 2>&1 | sudo tee log` also it create a log anywhere but i don't know where thus i Hope you know finally thanks you in advance to help myself fully repair this programs,

Regards.


Azaretdodo.
________________________________

**Comment by schung-amd** [comment] 2024-10-09 18:37
`sudo make -j 3 2>&1 | sudo tee log` should write the output to a file called "log" in the current directory. Also, I don't think you need `sudo` for this makefile by default, although you may need it for your system now.

**Comment by Azaretdodo** [comment] 2024-10-10 09:02
Hello,


No log file where it is advice as show bot printscreen,

![IMG_20241010_104710](https://github.com/user-attachments/assets/2443a3cc-b6d1-4277-99ca-4d560de2cbff)
![IMG_20241010_105516](https://github.com/user-attachments/assets/acf27700-088d-406e-abd6-4a6543f324c4)

Thus thanks you in advance if you have another help,

Regards.


Azaretdodo.

**Comment by schung-amd** [comment] 2024-10-10 14:03
Sorry, you're going to have to figure out where you're saving these logs or provide an image of the actual error, otherwise I am unable to provide further help. Since you're having issues with building a generic Linux kernel and not with any ROCm components, I also suggest seeking support in a more general Linux community, as this issue is not really relevant to ROCm itself at the moment.

**Comment by Azaretdodo** [comment] 2024-10-10 16:15
Hello again,


If you want i take a video of the compiling for show the error happening early also i will cut the video for show to you few printscreen finally thanks you in advance if you are agree,

Regards.


Azaretdodo.
________________________________

**Comment by schung-amd** [comment] 2024-10-10 17:09
The log file is there already, at `~/programs/ROCK-Kernel-Driver-rocm-6.0.0/log`.

**Comment by Azaretdodo** [comment] 2024-10-12 08:26
Hello,


Before you shoow the file also it wasn't there but now i show the errors gotten early with your help advice by this printscreen :

![IMG_20241012_101902](https://github.com/user-attachments/assets/8774ec79-7476-493a-bf9f-179a27867d0b)

Thanks you in advance if you have a nice advice now,

Regards.


Azaretdodo.

**Comment by schung-amd** [comment] 2024-10-22 14:29
You can try disabling the `-Werror` errors with environment variables:
`export CFLAGS="-Wno-error"`
`export CXXFLAGS="-Wno-error"`

**Comment by Azaretdodo** [comment] 2024-10-22 17:24
Hello,


If i disable these errors also i will compile fully ?

Thanks you in advance to answer this question,

Regards.


Azaretdodo.

________________________________
De : schung-amd ***@***.***>
Envoyé : mardi, octobre 22, 2024 4:30:01 PM
À : ROCm/ROCK-Kernel-Driver ***@***.***>
Cc : Azaretdodo ***@***.***>; Mention ***@***.***>
Objet : Re: [ROCm/ROCK-Kernel-Driver] conf.py error too after make menuconfig i happen error one and two by the line of command make (Issue #156)


You can try disabling the -Werror errors with environment variables:
export CFLAGS="-Wno-error"
export CXXFLAGS="-Wno-error"

**Comment by schung-amd** [comment] 2024-10-22 17:38
I can't guarantee that you won't see other errors somewhere, but this + the previous guidance on disabling SYSTEM_TRUSTED_KEYS and SYSTEM_REVOCATION_KEYS should address the errors you have shown.

**Comment by Azaretdodo** [comment] 2024-11-23 13:50
Hello,


Today i was try to follow both advices but the machine doesn't want to display any system also i have ask the repair to a friend administrator but because i think no have a real need of this machine i think lease it,

Have a nice weekend,

Regards.


Azaretdodo.
________________________________

**Comment by schung-amd** [comment] 2024-11-25 14:19
That's unfortunate to hear. I'm going to close this ticket for now, but you can continue commenting here for further guidance if needed once you have access to your system again (although, as stated before, this is general Linux guidance and not ROCm-related, so it doesn't really belong here). 

As an addendum, I did run into issues with this:

>export CFLAGS="-Wno-error"
export CXXFLAGS="-Wno-error"

but found another way to bypass these warnings is just to increase the value of `CONFIG_FRAME_WARN` in the kernel config to something like 4096, either through the `make menuconfig` UI or something like `scripts/config --set-val CONFIG_FRAME_WARN 4096`.

**Closed by schung-amd** 2024-11-25 14:19 UTC
Labels: Under Investigation
